version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - misspell
    - unconvert
    - unparam

linters-settings:
  gocyclo:
    min-complexity: 15

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - typecheck
