run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocyclo
    - goheader

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 15
  goheader:
    template: |
      Copyright 2024 SyndicateCode

      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
